# Generated by Django 4.1.7 on 2023-04-03 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("bloco", models.IntegerField()),
                ("andar", models.IntegerField()),
                ("apartamento", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("E", "Entregue"), ("P", "Pendente")], max_length=10
                    ),
                ),
                ("data_entrega", models.DateTimeField(auto_now_add=True)),
                ("entregue", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Morador",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("bloco", models.IntegerField()),
                ("apartamento", models.IntegerField()),
                ("andar", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
